import { useCallback, useEffect, useMemo, useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, View, Pressable, RefreshControl, useColorScheme } from 'react-native';
import { router } from 'expo-router';
import { Colors, Brand, Fonts, Spacing, BottomTabInset, MaxContentWidth, Radius } from '@/constants/theme';
import { fetchWatchlist, parsePct, StockItem } from '@/lib/api';
import { getBusinessDataset, summarizeBusinessDataset } from '@/lib/business-data';

export default function DataScreen(){
 const colors=useColorScheme()==='dark'?Colors.dark:Colors.light;
 const[stocks,setStocks]=useState<StockItem[]>([]),[dataset,setDataset]=useState<Awaited<ReturnType<typeof getBusinessDataset>>>(null),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(false);
 const load=useCallback(async()=>{try{setError(false);const[s,d]=await Promise.all([fetchWatchlist(),getBusinessDataset()]);setStocks(s);setDataset(d)}catch{setError(true)}finally{setRefreshing(false)}},[]);
 useEffect(()=>{load()},[load]);
 const market=useMemo(()=>{const priced=stocks.filter(s=>s.closingPrice!=null||s.lastPrice!=null);const p=priced.map(s=>parsePct(s.changePercent));const avg=p.length?p.reduce((a,b)=>a+b,0)/p.length:0;return{priced:priced.length,positive:p.filter(x=>x>0).length,negative:p.filter(x=>x<0).length,avg}},[stocks]);
 const summary=dataset?summarizeBusinessDataset(dataset):null;
 return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}} tintColor={Brand.dataViolet}/>} contentContainerStyle={[styles.content,{paddingBottom:BottomTabInset+Spacing.four}]}><View style={styles.wrap}>
   <View style={styles.header}><Text style={[styles.title,{color:colors.text}]}>تحلیل داده</Text><Text style={[styles.sub,{color:colors.textSecondary}]}>مرکز یکپارچه Data • EDA • KPI • Business Analytics</Text></View>
   <View style={styles.actions}><Pressable onPress={()=>router.push('/data-connect' as never)} style={[styles.action,{backgroundColor:colors.backgroundElement}]}><Text style={styles.icon}>🔌</Text><Text style={[styles.actionTitle,{color:colors.text}]}>اتصال داده</Text><Text style={[styles.actionText,{color:colors.textSecondary}]}>CSV / JSON / Excel و Sync حساب</Text></Pressable><Pressable onPress={()=>router.push('/modules' as never)} style={[styles.action,{backgroundColor:colors.backgroundElement}]}><Text style={styles.icon}>🧩</Text><Text style={[styles.actionTitle,{color:colors.text}]}>ماژول‌ها</Text><Text style={[styles.actionText,{color:colors.textSecondary}]}>EDA، KPI، SWOT، CRM، Pricing و Finance</Text></Pressable></View>
   <View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><View style={styles.cardHead}><View style={[styles.badge,{backgroundColor:dataset?'#14532d':'#374151'}]}><Text style={styles.badgeText}>{dataset?'SYNCED':'READY'}</Text></View><Text style={[styles.cardTitle,{color:colors.text}]}>داده شرکت</Text></View>{dataset&&summary?<><Text style={[styles.source,{color:colors.textSecondary}]}>{dataset.name} • {dataset.source}</Text><View style={styles.metrics}><Metric label="ردیف" value={summary.rows.toLocaleString('fa-IR')} colors={colors}/><Metric label="ستون" value={summary.columns.toLocaleString('fa-IR')} colors={colors}/><Metric label="کامل بودن" value={`${(summary.completeness*100).toLocaleString('fa-IR',{maximumFractionDigits:1})}٪`} colors={colors}/></View><Pressable onPress={()=>router.push('/modules' as never)} style={styles.primary}><Text style={styles.primaryText}>تحلیل با ماژول‌های تخصصی</Text></Pressable></>:<><Text style={[styles.empty,{color:colors.textSecondary}]}>هنوز dataset شرکتی متصل نیست. CSV/JSON را paste کنید یا فایل Excel انتخاب کنید.</Text><Pressable onPress={()=>router.push('/data-connect' as never)} style={styles.primary}><Text style={styles.primaryText}>اتصال داده واقعی</Text></Pressable></>}</View>
   <View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><View style={styles.cardHead}><View style={[styles.badge,{backgroundColor:'#1e3a8a'}]}><Text style={styles.badgeText}>MARKET</Text></View><Text style={[styles.cardTitle,{color:colors.text}]}>EDA بازار</Text></View><Text style={[styles.source,{color:colors.textSecondary}]}>خلاصه قیمت‌های تأییدشده watchlist؛ عدد ناموجود ساخته نمی‌شود.</Text><View style={styles.metrics}><Metric label="قیمت معتبر" value={market.priced.toLocaleString('fa-IR')} colors={colors}/><Metric label="مثبت" value={market.positive.toLocaleString('fa-IR')} colors={colors}/><Metric label="منفی" value={market.negative.toLocaleString('fa-IR')} colors={colors}/></View><Text style={[styles.avg,{color:market.avg>=0?Brand.positive:Brand.negative}]}>میانگین تغییر: {market.avg>=0?'+':''}{market.avg.toLocaleString('fa-IR',{maximumFractionDigits:2})}٪</Text><Pressable onPress={()=>router.push('/market' as never)} style={[styles.secondary,{borderColor:Brand.dataViolet}]}><Text style={[styles.secondaryText,{color:Brand.dataViolet}]}>باز کردن بازار و فیلترها</Text></Pressable></View>
   {error?<Text style={[styles.error,{color:Brand.warning}]}>بخشی از داده‌ها پاسخ نداد؛ برای تلاش دوباره صفحه را پایین بکشید.</Text>:null}
 </View></ScrollView></SafeAreaView>
}
function Metric({label,value,colors}:{label:string;value:string;colors:any}){return <View style={[styles.metric,{backgroundColor:colors.backgroundSelected}]}><Text style={[styles.metricValue,{color:colors.text}]}>{value}</Text><Text style={[styles.metricLabel,{color:colors.textSecondary}]}>{label}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1},content:{padding:Spacing.three},wrap:{maxWidth:MaxContentWidth,width:'100%',alignSelf:'center'},header:{alignItems:'flex-end',paddingVertical:Spacing.three},title:{fontFamily:Fonts.sans,fontSize:24,fontWeight:'900'},sub:{fontFamily:Fonts.sans,fontSize:11,marginTop:4},actions:{flexDirection:'row-reverse',gap:Spacing.two,marginBottom:Spacing.three},action:{flex:1,borderRadius:Radius.lg,padding:Spacing.three,alignItems:'flex-end'},icon:{fontSize:22},actionTitle:{fontFamily:Fonts.sans,fontSize:14,fontWeight:'900',marginTop:5},actionText:{fontFamily:Fonts.sans,fontSize:10,lineHeight:17,textAlign:'right',marginTop:3},card:{borderRadius:Radius.lg,padding:Spacing.four,marginBottom:Spacing.three},cardHead:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},cardTitle:{fontFamily:Fonts.sans,fontSize:16,fontWeight:'900'},badge:{borderRadius:12,paddingHorizontal:9,paddingVertical:4},badgeText:{color:'#fff',fontFamily:Fonts.mono,fontSize:9,fontWeight:'900'},source:{fontFamily:Fonts.sans,fontSize:10.5,lineHeight:18,textAlign:'right',marginTop:8},metrics:{flexDirection:'row-reverse',gap:Spacing.two,marginTop:Spacing.three},metric:{flex:1,borderRadius:Radius.md,padding:Spacing.three,alignItems:'center'},metricValue:{fontFamily:Fonts.mono,fontSize:17,fontWeight:'900'},metricLabel:{fontFamily:Fonts.sans,fontSize:9.5,marginTop:4},empty:{fontFamily:Fonts.sans,fontSize:11.5,lineHeight:20,textAlign:'right',marginTop:Spacing.three},avg:{fontFamily:Fonts.mono,fontSize:12,fontWeight:'800',textAlign:'right',marginTop:Spacing.three},primary:{backgroundColor:Brand.primary,borderRadius:Radius.md,paddingVertical:12,alignItems:'center',marginTop:Spacing.three},primaryText:{color:'#fff',fontFamily:Fonts.sans,fontSize:12,fontWeight:'900'},secondary:{borderWidth:1,borderRadius:Radius.md,paddingVertical:11,alignItems:'center',marginTop:Spacing.three},secondaryText:{fontFamily:Fonts.sans,fontSize:12,fontWeight:'900'},error:{fontFamily:Fonts.sans,fontSize:11,textAlign:'center'}});