import { ScrollView, SafeAreaView, StyleSheet, Text, View, Pressable, useColorScheme } from 'react-native';
import { router } from 'expo-router';
import { Brand, Colors, Fonts, MaxContentWidth, Radius, Spacing, BottomTabInset } from '@/constants/theme';

const STEPS = [
  { n: '۱', title: 'بازار سرمایه', body: 'از تب بازار نماد واقعی را پیدا کن، قیمت و داده CODAL را ببین و وارد جزئیات سهم شو.', action: 'باز کردن بازار', route: '/market' },
  { n: '۲', title: 'کیاشا AI', body: 'افق کوتاه‌مدت یا بلندمدت را انتخاب کن. کیا‌شا فقط نمادهایی را رتبه‌بندی می‌کند که داده واقعی کافی داشته باشند و تا ۳ BUY برتر را نشان می‌دهد.', action: 'رفتن به کیا‌شا', route: '/kiasha' },
  { n: '۳', title: 'Paper Trade', body: 'قبل از پول واقعی، سفارش Paper ثبت کن و بازده پرتفوی Paper را دنبال کن. Paper هیچ سفارشی به کارگزاری واقعی نمی‌فرستد.', action: 'دیدن پرتفوی', route: '/portfolio' },
  { n: '۴', title: 'تحلیل داده', body: 'برای EDA، KPI، Anomaly، Forecast و گزارش تحلیلی وارد ماژول‌ها شو. در Real Mode فقط داده متصل‌شده نمایش داده می‌شود.', action: 'ماژول‌های تحلیل', route: '/modules' },
  { n: '۵', title: 'توسعه کسب‌وکار', body: 'SWOT، CRM، Pricing، Journey و مدل مالی برای داده کسب‌وکار شماست؛ اگر منبع داده متصل نباشد BIAP عدد ساختگی نمایش نمی‌دهد.', action: 'توسعه کسب‌وکار', route: '/bizdev' },
  { n: '۶', title: 'معامله واقعی', body: 'پس از اتصال رسمی کارگزاری، واریز پول فقط در درگاه امن کارگزاری/PSP انجام می‌شود. BIAP اطلاعات کارت بانکی را دریافت یا نگهداری نمی‌کند.', action: 'وضعیت اتصال', route: '/kiasha-profile' },
] as const;

export default function HowToScreen() {
  const colors = useColorScheme() === 'dark' ? Colors.dark : Colors.light;
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}><ScrollView contentContainerStyle={[styles.content, { paddingBottom: BottomTabInset + Spacing.four }]}><View style={styles.wrap}>
    <View style={styles.header}><Text style={[styles.title, { color: colors.text }]}>چطور از BIAP استفاده کنم؟</Text><Text style={[styles.sub, { color: colors.textSecondary }]}>How to do it • مسیر ساده از داده تا تصمیم</Text></View>
    <View style={[styles.hero, { backgroundColor: colors.backgroundElement }]}><Text style={styles.heroTag}>BIAP GUIDE</Text><Text style={[styles.heroTitle, { color: colors.text }]}>داده واقعی → تحلیل → Paper → سرمایه‌گذاری</Text><Text style={[styles.heroBody, { color: colors.textSecondary }]}>هر بخش دمو یا Paper واضح برچسب می‌خورد. داده مالی ناموجود با fallback ساختگی پر نمی‌شود.</Text></View>
    {STEPS.map((step) => <View key={step.n} style={[styles.card, { backgroundColor: colors.backgroundElement }]}><View style={styles.cardTop}><View style={styles.num}><Text style={styles.numText}>{step.n}</Text></View><View style={{ flex: 1, alignItems: 'flex-end' }}><Text style={[styles.cardTitle, { color: colors.text }]}>{step.title}</Text><Text style={[styles.body, { color: colors.textSecondary }]}>{step.body}</Text></View></View><Pressable onPress={() => router.push(step.route as never)} style={styles.action}><Text style={styles.actionText}>{step.action} ←</Text></Pressable></View>)}
    <View style={[styles.tip, { backgroundColor: colors.backgroundElement }]}><Text style={[styles.tipTitle, { color: colors.text }]}>قانون اصلی BIAP</Text><Text style={[styles.body, { color: colors.textSecondary }]}>«واقعی»، «Paper» و «Demo» همیشه از هم جدا هستند. اگر منبع واقعی در دسترس نباشد، BIAP باید آن را ناموجود نشان دهد، نه اینکه عددی بسازد.</Text></View>
  </View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe:{flex:1}, content:{paddingHorizontal:Spacing.three}, wrap:{maxWidth:MaxContentWidth,width:'100%',alignSelf:'center'}, header:{paddingTop:Spacing.four,paddingBottom:Spacing.three,alignItems:'flex-end'}, title:{fontFamily:Fonts.sans,fontSize:24,fontWeight:'900'}, sub:{fontFamily:Fonts.sans,fontSize:11.5,marginTop:4}, hero:{borderRadius:Radius.lg,padding:Spacing.four,alignItems:'flex-end',marginBottom:Spacing.three}, heroTag:{fontFamily:Fonts.mono,fontSize:10,fontWeight:'900',color:'#8ab4ff'}, heroTitle:{fontFamily:Fonts.sans,fontSize:19,fontWeight:'900',textAlign:'right',marginTop:6}, heroBody:{fontFamily:Fonts.sans,fontSize:11.5,lineHeight:20,textAlign:'right',marginTop:6}, card:{borderRadius:Radius.md,padding:Spacing.three,marginBottom:Spacing.two}, cardTop:{flexDirection:'row-reverse',gap:Spacing.three,alignItems:'flex-start'}, num:{width:34,height:34,borderRadius:17,backgroundColor:Brand.primary,alignItems:'center',justifyContent:'center'}, numText:{color:'#fff',fontFamily:Fonts.sans,fontWeight:'900'}, cardTitle:{fontFamily:Fonts.sans,fontSize:15,fontWeight:'900'}, body:{fontFamily:Fonts.sans,fontSize:11.5,lineHeight:20,textAlign:'right',marginTop:4}, action:{alignSelf:'flex-end',marginTop:Spacing.two,paddingVertical:6}, actionText:{fontFamily:Fonts.sans,fontSize:11,fontWeight:'800',color:Brand.primary}, tip:{borderRadius:Radius.md,padding:Spacing.three,alignItems:'flex-end',marginTop:Spacing.two}, tipTitle:{fontFamily:Fonts.sans,fontSize:14,fontWeight:'900'} });
