import { ScrollView, SafeAreaView, StyleSheet, Text, View, Pressable, useColorScheme } from 'react-native';
import { router } from 'expo-router';
import { Brand, Colors, Fonts, MaxContentWidth, Radius, Spacing, BottomTabInset } from '@/constants/theme';

const STEPS = [
  { n: '۱', title: 'بازار و علاقه‌مندی‌ها', body: 'از تب بازار نماد واقعی را پیدا کن، وارد جزئیات سهم شو و با ☆ آن را به علاقه‌مندی‌ها اضافه کن. قیمت و تاریخچه فقط وقتی نمایش داده می‌شود که منبع معتبر در دسترس باشد.', action: 'باز کردن بازار', route: '/market' },
  { n: '۲', title: 'کیاشا AI', body: 'افق کوتاه‌مدت یا بلندمدت را انتخاب کن. کیا‌شا تا ۱۰ BUY معتبر را از داده واقعی رتبه‌بندی می‌کند و روی صفحه سهم نتیجه را به شکل GO / WAIT / NO-GO همراه با اندازه پیشنهادی نشان می‌دهد.', action: 'رفتن به کیا‌شا', route: '/kiasha' },
  { n: '۳', title: 'خرید، فروش و پیگیری', body: 'در Demo می‌توانی چند بار روی یک سهم خرید یا فروش ثبت کنی. در پیگیری دستی هم اگر قبلاً خریده‌ای، «خرید بیشتر» و «فروش» هر دو در دسترس می‌مانند. Portfolio و Orders باید همان کیف پول/حساب فعال را نشان دهند.', action: 'دیدن پرتفوی', route: '/portfolio' },
  { n: '۴', title: 'تحلیل داده واقعی', body: 'EDA، KPI، Anomaly، Dashboard و بعضی گزارش‌ها می‌توانند از منابع واقعی BIAP استفاده کنند. برای SQL، CRM، Pricing، Journey و داده اختصاصی شرکت باید منبع CSV/Excel، Database، CRM/ERP یا API به حساب متصل شود.', action: 'اتصال منبع داده', route: '/data-connect' },
  { n: '۵', title: 'Demo در برابر Real', body: 'در ماژول‌های تحلیل می‌توانی Demo Mode را برای دیدن نمونه رابط فعال کنی. در Real Mode فقط داده متصل نمایش داده می‌شود و اگر ورودی واقعی وجود نداشته باشد خروجی ساختگی ساخته نمی‌شود.', action: 'ماژول‌های تحلیل', route: '/modules' },
  { n: '۶', title: 'Auto Invest', body: 'Auto Invest هنوز برای استفاده عمومی فعال نیست و فعلاً به‌صورت بنر «به‌زودی» نمایش داده می‌شود. پس از آماده شدن اجرای امن و حساب مناسب، همین بخش فعال خواهد شد.', action: 'وضعیت کیا‌شا', route: '/kiasha' },
  { n: '۷', title: 'اتصال API کارگزاری', body: 'ارسال مستقیم سفارش از داخل BIAP فعلاً فعال نیست. پس از اتصال رسمی API یک کارگزاری مجاز، بنر اتصال API به مسیر واقعی خرید و فروش تبدیل می‌شود. اطلاعات کارت بانکی داخل BIAP نگهداری نمی‌شود.', action: 'مشاهده وضعیت', route: '/kiasha-profile' },
] as const;

export default function HowToScreen() {
  const colors = useColorScheme() === 'dark' ? Colors.dark : Colors.light;
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}><ScrollView contentContainerStyle={[styles.content, { paddingBottom: BottomTabInset + Spacing.four }]}><View style={styles.wrap}>
    <View style={styles.header}><Text style={[styles.title, { color: colors.text }]}>چطور از BIAP استفاده کنم؟</Text><Text style={[styles.sub, { color: colors.textSecondary }]}>How to do it • مسیر ساده از داده تا تصمیم</Text></View>
    <View style={[styles.hero, { backgroundColor: colors.backgroundElement }]}><Text style={styles.heroTag}>BIAP GUIDE</Text><Text style={[styles.heroTitle, { color: colors.text }]}>داده واقعی → کیا‌شا → تصمیم → پیگیری</Text><Text style={[styles.heroBody, { color: colors.textSecondary }]}>Real، Paper و Demo از هم جدا هستند. هرجا اتصال هنوز آماده نیست، BIAP آن را «به‌زودی» یا «منبع لازم است» نشان می‌دهد؛ نه اینکه داده یا اجرای واقعی را شبیه‌سازی کند.</Text></View>
    {STEPS.map((step) => <View key={step.n} style={[styles.card, { backgroundColor: colors.backgroundElement }]}><View style={styles.cardTop}><View style={styles.num}><Text style={styles.numText}>{step.n}</Text></View><View style={{ flex: 1, alignItems: 'flex-end' }}><Text style={[styles.cardTitle, { color: colors.text }]}>{step.title}</Text><Text style={[styles.body, { color: colors.textSecondary }]}>{step.body}</Text></View></View><Pressable onPress={() => router.push(step.route as never)} style={styles.action}><Text style={styles.actionText}>{step.action} ←</Text></Pressable></View>)}
    <View style={[styles.tip, { backgroundColor: colors.backgroundElement }]}><Text style={[styles.tipTitle, { color: colors.text }]}>قانون اصلی BIAP</Text><Text style={[styles.body, { color: colors.textSecondary }]}>«Real»، «Paper» و «Demo» همیشه از هم جدا هستند. اگر داده معتبر یا اتصال رسمی وجود نداشته باشد، نتیجه باید ناموجود بماند. این قانون برای قیمت، تحلیل، عملکرد، Auto Invest و اتصال کارگزاری یکسان است.</Text></View>
  </View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe:{flex:1}, content:{paddingHorizontal:Spacing.three}, wrap:{maxWidth:MaxContentWidth,width:'100%',alignSelf:'center'}, header:{paddingTop:Spacing.four,paddingBottom:Spacing.three,alignItems:'flex-end'}, title:{fontFamily:Fonts.sans,fontSize:24,fontWeight:'900'}, sub:{fontFamily:Fonts.sans,fontSize:11.5,marginTop:4}, hero:{borderRadius:Radius.lg,padding:Spacing.four,alignItems:'flex-end',marginBottom:Spacing.three}, heroTag:{fontFamily:Fonts.mono,fontSize:10,fontWeight:'900',color:'#8ab4ff'}, heroTitle:{fontFamily:Fonts.sans,fontSize:19,fontWeight:'900',textAlign:'right',marginTop:6}, heroBody:{fontFamily:Fonts.sans,fontSize:11.5,lineHeight:20,textAlign:'right',marginTop:6}, card:{borderRadius:Radius.md,padding:Spacing.three,marginBottom:Spacing.two}, cardTop:{flexDirection:'row-reverse',gap:Spacing.three,alignItems:'flex-start'}, num:{width:34,height:34,borderRadius:17,backgroundColor:Brand.primary,alignItems:'center',justifyContent:'center'}, numText:{color:'#fff',fontFamily:Fonts.sans,fontWeight:'900'}, cardTitle:{fontFamily:Fonts.sans,fontSize:15,fontWeight:'900'}, body:{fontFamily:Fonts.sans,fontSize:11.5,lineHeight:20,textAlign:'right',marginTop:4}, action:{alignSelf:'flex-end',marginTop:Spacing.two,paddingVertical:6}, actionText:{fontFamily:Fonts.sans,fontSize:11,fontWeight:'800',color:Brand.primary}, tip:{borderRadius:Radius.md,padding:Spacing.three,alignItems:'flex-end',marginTop:Spacing.two}, tipTitle:{fontFamily:Fonts.sans,fontSize:14,fontWeight:'900'} });