import { ScrollView, SafeAreaView, StyleSheet, Text, View, Pressable, useColorScheme } from 'react-native';
import { router } from 'expo-router';
import { Brand, Colors, Fonts, MaxContentWidth, Radius, Spacing, BottomTabInset } from '@/constants/theme';

const STEPS = [
  { n: '۱', title: 'بازار و علاقه‌مندی‌ها', body: 'از تب بازار نماد را جست‌وجو کن، وارد جزئیات سهم شو و با ☆ آن را به علاقه‌مندی‌ها اضافه کن. قیمت، تاریخچه و اطلاعاتی که منبع معتبر ندارند عمداً با «—» نمایش داده می‌شوند.', action: 'باز کردن بازار', route: '/market' },
  { n: '۲', title: 'نظر نهایی کیا‌شا', body: 'کیا‌شا تحلیل چندعاملی را به یک تصمیم واضح تبدیل می‌کند: GO برای خرید قابل بررسی، WAIT برای صبر و NO-GO برای ورود نکردن. اگر BUY باشد، مبلغ پیشنهادی نیز با توجه به موجودی و محدودیت ریسک محاسبه می‌شود.', action: 'رفتن به کیا‌شا', route: '/kiasha' },
  { n: '۳', title: 'موتور ۶ عاملی', body: 'بنیادی، ریسک، پیش‌بینی، مقایسه، تکنیکال و جریان پول با هم رأی می‌دهند. نمودار موتور کیا‌شا نشان می‌دهد کدام عامل داده/ارزیابی واقعی دارد و چه زمانی وزن‌دهی مشاهده‌شده فعال شده است.', action: 'مشاهده موتور کیا‌شا', route: '/kiasha' },
  { n: '۴', title: 'خرید، فروش و خرید بیشتر', body: 'در Demo می‌توانی چند بار روی یک سهم خرید کنی، دوباره به موقعیت اضافه کنی یا بفروشی. در حالت دستی نیز اگر قبلاً سهم را خریده‌ای، «خرید بیشتر» و «فروش» هر دو در دسترس می‌مانند و میانگین خرید به‌روزرسانی می‌شود.', action: 'دیدن سفارش‌ها', route: '/orders' },
  { n: '۵', title: 'پرتفوی و موجودی', body: 'پرتفوی، سفارش‌ها و موجودی باید از همان حساب Demo یا Paper خوانده شوند. Demo و Paper از هم جدا هستند و خرید واقعی کارگزاری با این دو مخلوط نمی‌شود.', action: 'دیدن پرتفوی', route: '/portfolio' },
  { n: '۶', title: 'Auto Invest', body: 'Auto Invest هنوز برای استفاده عمومی فعال نشده و فعلاً با برچسب «به‌زودی» نمایش داده می‌شود. پس از تکمیل داده، کنترل ریسک و اجرای پایدار Paper می‌توان آن را فعال کرد.', action: 'صفحه کیا‌شا', route: '/kiasha' },
  { n: '۷', title: 'اتصال API کارگزاری', body: 'ارسال مستقیم سفارش هنوز فعال نیست. بخش اتصال API با وضعیت SOON نمایش داده می‌شود تا بعداً فقط با منبع رسمی و مجاز کارگزاری فعال شود. BIAP اطلاعات کارت بانکی را دریافت یا نگهداری نمی‌کند.', action: 'وضعیت کیا‌شا', route: '/kiasha-profile' },
  { n: '۸', title: 'تحلیل داده', body: 'هر ماژول دو حالت دارد: Demo برای دیدن نمونه رابط کاربری، و Real برای داده واقعی متصل. EDA، Dashboard، KPI، Anomaly، Governance و برخی گزارش‌ها همین حالا می‌توانند از داده واقعی BIAP خروجی بسازند؛ ماژول‌هایی که داده اختصاصی شرکت لازم دارند تا زمان اتصال منبع، عدد ساختگی تولید نمی‌کنند.', action: 'ماژول‌های تحلیل', route: '/modules' },
  { n: '۹', title: 'توسعه کسب‌وکار', body: 'SWOT، CRM، Journey، Pricing، Business Plan، Financial Model و ابزارهای مشابه برای خروجی واقعی به داده شرکت شما نیاز دارند. در نبود CRM/SQL/فایل مالی متصل، Real Mode صریحاً اعلام می‌کند که ورودی لازم است.', action: 'توسعه کسب‌وکار', route: '/bizdev' },
] as const;

export default function HowToScreen() {
  const colors = useColorScheme() === 'dark' ? Colors.dark : Colors.light;
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.background }]}><ScrollView contentContainerStyle={[styles.content, { paddingBottom: BottomTabInset + Spacing.four }]}><View style={styles.wrap}>
    <View style={styles.header}><Text style={[styles.title, { color: colors.text }]}>چطور از BIAP استفاده کنم؟</Text><Text style={[styles.sub, { color: colors.textSecondary }]}>How to do it • نسخه فعلی مسیر کاربر</Text></View>
    <View style={[styles.hero, { backgroundColor: colors.backgroundElement }]}><Text style={styles.heroTag}>BIAP GUIDE</Text><Text style={[styles.heroTitle, { color: colors.text }]}>داده واقعی → تحلیل کیا‌شا → تصمیم → Demo / Paper</Text><Text style={[styles.heroBody, { color: colors.textSecondary }]}>سه وضعیت همیشه از هم جدا هستند: Real برای داده واقعی، Paper برای اجرای آزمایشی سرور و Demo برای تست محلی. اگر داده معتبر نباشد، BIAP عدد یا سیگنال ساختگی تولید نمی‌کند.</Text></View>
    <View style={[styles.legend, { backgroundColor: colors.backgroundElement }]}><View style={styles.legendItem}><Text style={[styles.legendText, { color: colors.textSecondary }]}>داده واقعی متصل</Text><View style={[styles.dot, { backgroundColor: Brand.stockGreen }]} /></View><View style={styles.legendItem}><Text style={[styles.legendText, { color: colors.textSecondary }]}>Paper / آزمایشی سرور</Text><View style={[styles.dot, { backgroundColor: Brand.primary }]} /></View><View style={styles.legendItem}><Text style={[styles.legendText, { color: colors.textSecondary }]}>Demo / نمونه و تست</Text><View style={[styles.dot, { backgroundColor: '#7048e8' }]} /></View></View>
    {STEPS.map((step) => <View key={step.n} style={[styles.card, { backgroundColor: colors.backgroundElement }]}><View style={styles.cardTop}><View style={styles.num}><Text style={styles.numText}>{step.n}</Text></View><View style={{ flex: 1, alignItems: 'flex-end' }}><Text style={[styles.cardTitle, { color: colors.text }]}>{step.title}</Text><Text style={[styles.body, { color: colors.textSecondary }]}>{step.body}</Text></View></View><Pressable onPress={() => router.push(step.route as never)} style={styles.action}><Text style={styles.actionText}>{step.action} ←</Text></Pressable></View>)}
    <View style={[styles.tip, { backgroundColor: colors.backgroundElement }]}><Text style={[styles.tipTitle, { color: colors.text }]}>قانون اصلی BIAP</Text><Text style={[styles.body, { color: colors.textSecondary }]}>اگر صفحه‌ای در Real Mode داده کافی ندارد، همان نبود داده باید دیده شود. Demo فقط برای نمایش و تست است و نباید جای داده واقعی را بگیرد.</Text></View>
  </View></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe:{flex:1}, content:{paddingHorizontal:Spacing.three}, wrap:{maxWidth:MaxContentWidth,width:'100%',alignSelf:'center'}, header:{paddingTop:Spacing.four,paddingBottom:Spacing.three,alignItems:'flex-end'}, title:{fontFamily:Fonts.sans,fontSize:24,fontWeight:'900'}, sub:{fontFamily:Fonts.sans,fontSize:11.5,marginTop:4}, hero:{borderRadius:Radius.lg,padding:Spacing.four,alignItems:'flex-end',marginBottom:Spacing.three}, heroTag:{fontFamily:Fonts.mono,fontSize:10,fontWeight:'900',color:'#8ab4ff'}, heroTitle:{fontFamily:Fonts.sans,fontSize:19,fontWeight:'900',textAlign:'right',marginTop:6}, heroBody:{fontFamily:Fonts.sans,fontSize:11.5,lineHeight:20,textAlign:'right',marginTop:6}, legend:{borderRadius:Radius.md,padding:Spacing.three,marginBottom:Spacing.three,gap:8}, legendItem:{flexDirection:'row-reverse',alignItems:'center',gap:8}, legendText:{fontFamily:Fonts.sans,fontSize:10.5}, dot:{width:8,height:8,borderRadius:4}, card:{borderRadius:Radius.md,padding:Spacing.three,marginBottom:Spacing.two}, cardTop:{flexDirection:'row-reverse',gap:Spacing.three,alignItems:'flex-start'}, num:{width:34,height:34,borderRadius:17,backgroundColor:Brand.primary,alignItems:'center',justifyContent:'center'}, numText:{color:'#fff',fontFamily:Fonts.sans,fontWeight:'900'}, cardTitle:{fontFamily:Fonts.sans,fontSize:15,fontWeight:'900'}, body:{fontFamily:Fonts.sans,fontSize:11.5,lineHeight:20,textAlign:'right',marginTop:4}, action:{alignSelf:'flex-end',marginTop:Spacing.two,paddingVertical:6}, actionText:{fontFamily:Fonts.sans,fontSize:11,fontWeight:'800',color:Brand.primary}, tip:{borderRadius:Radius.md,padding:Spacing.three,alignItems:'flex-end',marginTop:Spacing.two}, tipTitle:{fontFamily:Fonts.sans,fontSize:14,fontWeight:'900'} });