import { useCallback, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { BottomTabInset, Brand, Colors, Fonts, MaxContentWidth, Radius, Spacing } from '@/constants/theme';
import { fetchGlobalStatus } from '@/lib/global-api';
import { getGlobalMarketSelection, type GlobalMarketSelection } from '@/lib/global-market-selection';

export default function GlobalExecutionScreen(){
  const colors=useColorScheme()==='dark'?Colors.dark:Colors.light;
  const[market,setMarket]=useState<GlobalMarketSelection|null>(null);const[status,setStatus]=useState<Record<string,unknown>|null>(null);
  useFocusEffect(useCallback(()=>{Promise.all([getGlobalMarketSelection(),fetchGlobalStatus()]).then(([m,s])=>{setMarket(m);setStatus(s)});},[]));
  const liveBroker=Boolean(status?.liveBrokerConnected);const liveTrading=Boolean(status?.liveTrading);const switchRequested=Boolean(status?.liveTradingSwitchRequested);
  return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={styles.content}><View style={styles.max}>
    <View style={styles.header}><Pressable onPress={()=>router.back()} style={[styles.back,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.backText,{color:colors.text}]}>← Back</Text></Pressable><View style={{flex:1}}><Text style={[styles.title,{color:colors.text}]}>Orders & Execution</Text><Text style={[styles.sub,{color:colors.textSecondary}]}>Global execution is isolated from the Iran order history and broker paths.</Text></View></View>

    <View style={[styles.hero,{backgroundColor:colors.backgroundElement}]}><Text style={styles.eyebrow}>ACTIVE MARKET</Text><Text style={[styles.market,{color:colors.text}]}>{market?`${market.countryName} • ${market.exchangeLabel}`:'Loading…'}</Text><Text style={[styles.meta,{color:colors.textSecondary}]}>{market?`${market.mic||market.exchange} • ${market.currency}`:''}</Text></View>

    <View style={styles.statusGrid}><View style={[styles.statusCard,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.statusValue,{color:Brand.positive}]}>PAPER</Text><Text style={[styles.statusLabel,{color:colors.textSecondary}]}>Current execution mode</Text></View><View style={[styles.statusCard,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.statusValue,{color:liveBroker?Brand.positive:colors.textSecondary}]}>{liveBroker?'CONNECTED':'NONE'}</Text><Text style={[styles.statusLabel,{color:colors.textSecondary}]}>Live broker</Text></View><View style={[styles.statusCard,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.statusValue,{color:liveTrading?Brand.positive:Brand.warning}]}>{liveTrading?'ON':'OFF'}</Text><Text style={[styles.statusLabel,{color:colors.textSecondary}]}>Live trading</Text></View></View>

    <View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Why there are no Global live orders here yet</Text><Text style={[styles.body,{color:colors.textSecondary}]}>BIAP Global can analyze markets and construct a paper portfolio, but sending an order requires a market-aware broker adapter, contract identifiers, trading permissions, lot sizes, fees, FX, audit logging and final risk checks. The Iran Paper/Order history is intentionally not reused for Global markets.</Text></View>

    <View style={[styles.flow,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Execution pipeline</Text>{['Kiasha / Stock Analysis','Evidence + Risk Gate','Portfolio Agent','Paper Order Draft','Human Approval','Future Regulated Broker Adapter'].map((item,index)=><View key={item} style={styles.step}><View style={[styles.number,{backgroundColor:index<4?Brand.primary:colors.backgroundSelected}]}><Text style={styles.numberText}>{index+1}</Text></View><Text style={[styles.stepText,{color:colors.text}]}>{item}</Text></View>)}</View>

    {switchRequested&&!liveTrading?<View style={[styles.warning,{borderColor:Brand.warning}]}><Text style={[styles.warningTitle,{color:Brand.warning}]}>Live switch requested but not enabled</Text><Text style={[styles.body,{color:colors.textSecondary}]}>The backend still reports liveTrading=false. BIAP will not bypass this gate.</Text></View>:null}

    <Pressable onPress={()=>router.push('/portfolio')} style={[styles.primary,{backgroundColor:Brand.primary}]}><Text style={styles.primaryText}>Build a Global paper portfolio</Text></Pressable><Pressable onPress={()=>router.push('/market')} style={[styles.secondary,{borderColor:Brand.primary}]}><Text style={styles.secondaryText}>Open Market</Text></Pressable>

    <Text style={[styles.disclaimer,{color:colors.textSecondary}]}>No live order is transmitted from this screen. A future Global broker integration must be explicit and separate from the Iran production execution path.</Text>
  </View></ScrollView></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:Spacing.three,paddingBottom:BottomTabInset+Spacing.six},max:{maxWidth:MaxContentWidth,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'flex-start',gap:12,paddingTop:Spacing.four,paddingBottom:Spacing.three},back:{paddingHorizontal:11,paddingVertical:8,borderRadius:18},backText:{fontFamily:Fonts.sans,fontSize:10,fontWeight:'800'},title:{fontFamily:Fonts.sans,fontSize:22,fontWeight:'900'},sub:{fontFamily:Fonts.sans,fontSize:10,lineHeight:15,marginTop:3},hero:{borderRadius:Radius.lg,padding:Spacing.four},eyebrow:{color:Brand.primary,fontFamily:Fonts.mono,fontSize:8.5,fontWeight:'900'},market:{fontFamily:Fonts.sans,fontSize:17,fontWeight:'900',marginTop:5},meta:{fontFamily:Fonts.mono,fontSize:9,marginTop:3},statusGrid:{flexDirection:'row',gap:8,marginTop:10},statusCard:{flex:1,borderRadius:Radius.md,paddingVertical:14,paddingHorizontal:6,alignItems:'center'},statusValue:{fontFamily:Fonts.mono,fontSize:12,fontWeight:'900',textAlign:'center'},statusLabel:{fontFamily:Fonts.sans,fontSize:8,textAlign:'center',marginTop:4},card:{borderRadius:Radius.lg,padding:Spacing.four,marginTop:14},cardTitle:{fontFamily:Fonts.sans,fontSize:13,fontWeight:'900'},body:{fontFamily:Fonts.sans,fontSize:10,lineHeight:16,marginTop:6},flow:{borderRadius:Radius.lg,padding:Spacing.four,marginTop:12},step:{flexDirection:'row',alignItems:'center',gap:10,marginTop:10},number:{width:26,height:26,borderRadius:13,alignItems:'center',justifyContent:'center'},numberText:{color:'#fff',fontFamily:Fonts.mono,fontSize:9,fontWeight:'900'},stepText:{fontFamily:Fonts.sans,fontSize:10.5,fontWeight:'700'},warning:{borderWidth:1,borderRadius:Radius.md,padding:12,marginTop:12},warningTitle:{fontFamily:Fonts.sans,fontSize:11,fontWeight:'900'},primary:{minHeight:48,borderRadius:Radius.md,alignItems:'center',justifyContent:'center',marginTop:14},primaryText:{color:'#fff',fontFamily:Fonts.sans,fontSize:10.5,fontWeight:'900'},secondary:{minHeight:46,borderRadius:Radius.md,borderWidth:1,alignItems:'center',justifyContent:'center',marginTop:8},secondaryText:{color:Brand.primary,fontFamily:Fonts.sans,fontSize:10.5,fontWeight:'900'},disclaimer:{fontFamily:Fonts.sans,fontSize:8.5,lineHeight:14,textAlign:'center',marginTop:18}});