import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View, useColorScheme } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Constants from 'expo-constants';
import { Colors, Brand, Fonts, Spacing, BottomTabInset, MaxContentWidth, Radius, ThemeColors } from '@/constants/theme';
import { useLogout } from '@/lib/logout-context';
import { authFetch, logoutAndClearAuthSession, storeAuthPayload } from '@/lib/auth-session';
import { API_BASE } from '@/lib/api';
import { getClientContext } from '@/lib/activity';

type UserData={name?:string;fullName?:string;email?:string;id?:string|number;userId?:string|number};

function Avatar({name}:{name:string;colors:ThemeColors}){const words=name.trim().split(/\s+/);const initials=words.length>1?(words[0][0]??'')+(words[1][0]??''):(name[0]??'');return <View style={[avatarStyles.circle,{backgroundColor:Brand.primary}]}><Text style={avatarStyles.text}>{initials||'?'}</Text></View>}
const avatarStyles=StyleSheet.create({circle:{width:80,height:80,borderRadius:40,alignItems:'center',justifyContent:'center'},text:{color:'#fff',fontSize:28,fontWeight:'700'}});
function InfoCard({label,value,colors}:{label:string;value:string;colors:ThemeColors}){return <View style={[infoStyles.row,{borderBottomColor:colors.backgroundSelected}]}><Text style={[infoStyles.lbl,{color:colors.textSecondary}]}>{label}</Text><Text style={[infoStyles.val,{color:colors.text}]}>{value}</Text></View>}
const infoStyles=StyleSheet.create({row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:Spacing.three,borderBottomWidth:StyleSheet.hairlineWidth,gap:12},lbl:{fontFamily:Fonts.sans,fontSize:13},val:{fontFamily:Fonts.sans,fontSize:13,flexShrink:1,textAlign:'right'}});

export default function ProfileScreen(){
  const colors=useColorScheme()==='dark'?Colors.dark:Colors.light;const logout=useLogout();const[user,setUser]=useState<UserData|null>(null);const[currentPassword,setCurrentPassword]=useState('');const[newPassword,setNewPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[changing,setChanging]=useState(false);const[passwordError,setPasswordError]=useState('');const[passwordMessage,setPasswordMessage]=useState('');
  useEffect(()=>{AsyncStorage.getItem('user').then(raw=>{if(raw){try{setUser(JSON.parse(raw))}catch{setUser(null)}}})},[]);
  const handleLogout=()=>Alert.alert('Sign out','Are you sure you want to sign out?',[{text:'Cancel',style:'cancel'},{text:'Sign out',style:'destructive',onPress:async()=>{await logoutAndClearAuthSession();logout()}}]);
  const changePassword=async()=>{setPasswordError('');setPasswordMessage('');if(!currentPassword){setPasswordError('Enter your current password.');return}if(newPassword.length<8){setPasswordError('The new password must contain at least 8 characters.');return}if(newPassword!==confirmPassword){setPasswordError('The new passwords do not match.');return}setChanging(true);try{const context=await getClientContext();const res=await authFetch(`${API_BASE}/auth/change-password`,{method:'POST',body:JSON.stringify({currentPassword,newPassword,...context})});const data=await res.json().catch(()=>({}));if(!res.ok){setPasswordError(data?.error||'Password change failed.');return}if(data?.accessToken)await storeAuthPayload(data);setCurrentPassword('');setNewPassword('');setConfirmPassword('');setPasswordMessage('Password changed. Previous sessions were closed.')}catch{setPasswordError('Could not connect to the server.')}finally{setChanging(false)}};
  const displayName=user?.fullName??user?.name??user?.email?.split('@')[0]??'User';const id=user?.userId??user?.id;const appVersion=Constants.expoConfig?.version??Constants.nativeAppVersion??'—';

  return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={[styles.content,{paddingBottom:BottomTabInset+Spacing.four}]} keyboardShouldPersistTaps="handled"><View style={{maxWidth:MaxContentWidth,width:'100%',alignSelf:'center'}}>
    <View style={styles.header}><Text style={[styles.headerTitle,{color:colors.text}]}>Profile & Settings</Text></View>
    <View style={[styles.avatarSection,{backgroundColor:colors.backgroundElement}]}><Avatar name={displayName} colors={colors}/><Text style={[styles.displayName,{color:colors.text}]}>{displayName}</Text>{user?.email?<Text style={[styles.email,{color:colors.textSecondary}]}>{user.email}</Text>:null}</View>
    {user?<View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Account</Text><InfoCard label="Name" value={displayName} colors={colors}/>{user.email?<InfoCard label="Email" value={user.email} colors={colors}/>:null}{id?<InfoCard label="User ID" value={String(id)} colors={colors}/>:null}</View>:null}
    <View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.cardTitle,{color:colors.text}]}>Change password</Text><Text style={[styles.cardHint,{color:colors.textSecondary}]}>Changing your password closes previous account sessions.</Text><TextInput placeholder="Current password" placeholderTextColor={colors.textSecondary} secureTextEntry value={currentPassword} onChangeText={setCurrentPassword} style={[styles.input,{color:colors.text,borderColor:colors.backgroundSelected,backgroundColor:colors.background}]}/><TextInput placeholder="New password (minimum 8 characters)" placeholderTextColor={colors.textSecondary} secureTextEntry value={newPassword} onChangeText={setNewPassword} style={[styles.input,{color:colors.text,borderColor:colors.backgroundSelected,backgroundColor:colors.background}]}/><TextInput placeholder="Confirm new password" placeholderTextColor={colors.textSecondary} secureTextEntry value={confirmPassword} onChangeText={setConfirmPassword} style={[styles.input,{color:colors.text,borderColor:colors.backgroundSelected,backgroundColor:colors.background}]}/>{passwordError?<Text style={styles.error}>{passwordError}</Text>:null}{passwordMessage?<Text style={styles.success}>{passwordMessage}</Text>:null}<Pressable onPress={()=>{void changePassword()}} disabled={changing} style={[styles.passwordButton,{backgroundColor:Brand.primary,opacity:changing?.65:1}]}>{changing?<ActivityIndicator color="#fff"/>:<Text style={styles.passwordButtonText}>Save new password</Text>}</Pressable></View>
    <View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.cardTitle,{color:colors.text}]}>About</Text><InfoCard label="App" value="BIAP Global" colors={colors}/><InfoCard label="Version" value={appVersion} colors={colors}/><InfoCard label="Global API" value="biap.dadashi.no/global-api" colors={colors}/></View>
    <Pressable style={({pressed})=>[styles.logoutBtn,{backgroundColor:'#3d1a1a',opacity:pressed?.75:1}]} onPress={handleLogout}><Text style={styles.logoutText}>Sign out</Text></Pressable>
  </View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:Spacing.three},header:{paddingTop:Spacing.four,paddingBottom:Spacing.three},headerTitle:{fontSize:22,fontFamily:Fonts.sans,fontWeight:'900'},avatarSection:{alignItems:'center',gap:Spacing.two,borderRadius:Spacing.three,paddingVertical:Spacing.four,marginBottom:Spacing.three},displayName:{fontSize:20,fontFamily:Fonts.sans,fontWeight:'800'},email:{fontSize:13,fontFamily:Fonts.mono},card:{borderRadius:Spacing.two,padding:Spacing.three,marginBottom:Spacing.three},cardTitle:{fontFamily:Fonts.sans,fontSize:15,marginBottom:Spacing.two,fontWeight:'800'},cardHint:{fontFamily:Fonts.sans,fontSize:11,lineHeight:18,marginBottom:Spacing.two},input:{borderWidth:1,borderRadius:Radius.md,paddingHorizontal:Spacing.three,paddingVertical:12,marginBottom:Spacing.two,fontSize:13,fontFamily:Fonts.sans},passwordButton:{borderRadius:Radius.md,paddingVertical:13,alignItems:'center',marginTop:Spacing.one},passwordButtonText:{color:'#fff',fontFamily:Fonts.sans,fontWeight:'800',fontSize:13},error:{color:Brand.negative,fontFamily:Fonts.sans,fontSize:11,marginBottom:6},success:{color:Brand.positive,fontFamily:Fonts.sans,fontSize:11,marginBottom:6},logoutBtn:{borderRadius:Spacing.two,paddingVertical:Spacing.three,alignItems:'center',marginTop:Spacing.two},logoutText:{color:Brand.negative,fontFamily:Fonts.sans,fontSize:15,fontWeight:'800'}});