import { authFetch, authHeaders } from '@/lib/auth-session';

export const API_BASE = 'https://biap.dadashi.no/api';
export const KIASHA_API_BASE = process.env.EXPO_PUBLIC_KIASHA_API_BASE || API_BASE;
export type StockItem={name:string;code:string;lastPrice?:number;closingPrice?:number;yesterdayPrice?:number;change?:number;changePercent?:string|number;error?:boolean};export type WatchlistResponse={symbols:StockItem[]};
async function getHeaders():Promise<Record<string,string>>{return authHeaders()}
export async function fetchWatchlist(timeoutMs=10_000):Promise<StockItem[]>{const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const headers=await getHeaders();const r=await authFetch(`${API_BASE}/stock/watchlist`,{headers,signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j:WatchlistResponse=await r.json();return j.symbols??[]}finally{clearTimeout(t)}}
export function formatPrice(n?:number){return n==null?'—':n.toLocaleString('fa-IR')}export function parsePct(raw?:string|number){return Number(raw)||0}
export type RecommendationCall='BUY'|'HOLD'|'SELL';export type RecommendationBreakdownEntry={agent:string;vote:number;confidence:number;trust_score?:number;maturity?:string;weight_pre_norm?:number;reasoning:string;weight_normalized:number};
export type Recommendation={code:string;name?:string|null;call:RecommendationCall;score:number;generatedAt:string;dataSource:'mock'|'live'|'codal';dataAvailability:{codal:boolean;codal_metadata?:boolean;market_extended:boolean};codalMetadata?:Record<string,unknown>|null;codalFundamentals?:{symbol?:string;revenue_yoy_pct?:number|null;net_margin_pct?:number|null;net_margin_prev_pct?:number|null;total_assets_current?:number|null;total_liabilities_current?:number|null;total_equity_current?:number|null;audit_opinion?:string|null;related_party_flags?:number|null;report_title?:string|null;report_scope?:string|null}|null;livePrice:{lastPrice?:number|null;closingPrice?:number|null;yesterdayPrice?:number|null;changePercent?:number|null}|null;extendedMarket?:{dayLow?:number|null;dayHigh?:number|null;volumeToday?:number|null;tradeValueToday?:number|null;tradeCountToday?:number|null;avgVolume30d?:number|null;price52wHigh?:number|null;price52wLow?:number|null;pe?:number|null;sectorAvgPe?:number|null;epsValue?:number|null;estimatedEps?:number|null;marketCap?:number|null;marketCapBn?:number|null;sharesOutstanding?:number|null;sectorName?:string|null}|null;breakdown:RecommendationBreakdownEntry[]};
async function sleep(ms:number){await new Promise(r=>setTimeout(r,ms))}export async function fetchRecommendation(code:string,timeoutMs=15_000):Promise<Recommendation|null>{for(let a=0;a<2;a++){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const headers=await getHeaders();const r=await authFetch(`${KIASHA_API_BASE}/stock/recommendation/${encodeURIComponent(code)}`,{headers,signal:c.signal});if(r.status===503&&a===0){await sleep(1200);continue}if(!r.ok)return null;return await r.json()}catch{return null}finally{clearTimeout(t)}}return null}
export type RiskDecision={allowed:boolean;reasons:string[];checks:Record<string,boolean>};export type OrderIntent={id:string;code:string;side:'BUY'|'SELL';quantity:number;limit_price:number|null;mode:string;status:string;recommendation_call:string;recommendation_score:number;created_at:string;note:string};export type OrderPreviewResult={ok:true;intent:OrderIntent;risk:RiskDecision}|{ok:false;riskRejected:true;risk:RiskDecision;message:string}|{ok:false;riskRejected:false;message:string};
export async function previewPaperOrder(params:{code:string;side:'BUY'|'SELL';quantity:number}):Promise<OrderPreviewResult>{try{const headers=await getHeaders(),r=await authFetch(`${KIASHA_API_BASE}/orders/preview`,{method:'POST',headers,body:JSON.stringify({...params,mode:'paper'})}),d=await r.json();if(!r.ok){const risk=d?.detail?.risk as RiskDecision|undefined;return risk?{ok:false,riskRejected:true,risk,message:d?.detail?.message??'رد شد توسط ریسک'}:{ok:false,riskRejected:false,message:typeof d?.detail==='string'?d.detail:'خطا در پیش‌نمایش سفارش'}}return{ok:true,intent:d.intent,risk:d.risk}}catch{return{ok:false,riskRejected:false,message:'اتصال به سرور برقرار نشد'}}}
export async function submitPaperOrder(intentId:string):Promise<{ok:true;receipt:OrderIntent&{submittedAt:string;broker:string|null;brokerOrderId:string|null}}|{ok:false;message:string}>{try{const headers=await getHeaders(),r=await authFetch(`${KIASHA_API_BASE}/orders/submit`,{method:'POST',headers,body:JSON.stringify({intentId})}),d=await r.json();return r.ok?{ok:true,receipt:d}:{ok:false,message:typeof d?.detail==='string'?d.detail:'خطا در ثبت سفارش'}}catch{return{ok:false,message:'اتصال به سرور برقرار نشد'}}}
export type OrderReceipt=OrderIntent&{submittedAt?:string;broker?:string|null;brokerOrderId?:string|null;rejectionReason?:string};export async function fetchOrderHistory(limit=100,timeoutMs=10_000):Promise<OrderReceipt[]|null>{const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const headers=await getHeaders(),r=await authFetch(`${KIASHA_API_BASE}/audit/orders?limit=${limit}`,{headers,signal:c.signal});if(!r.ok)return null;const j=await r.json();return(Array.isArray(j?.items)?j.items as OrderReceipt[]:[]).filter(x=>Boolean(x.submittedAt))}catch{return null}finally{clearTimeout(t)}}
export type MarketSymbolResult={code:string;symbol:string;name:string;market?:string|null;last_price?:number|null;closing_price?:number|null;yesterday_price?:number|null;change_percent?:number|null};export async function fetchSymbols(params:{q?:string;market?:'TSE'|'IFB'|'IFB_BASE';limit?:number},timeoutMs=10_000):Promise<MarketSymbolResult[]>{const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const q=new URLSearchParams();if(params.q)q.set('q',params.q);if(params.market)q.set('market',params.market);if(params.limit)q.set('limit',String(params.limit));const headers=await getHeaders(),r=await authFetch(`${KIASHA_API_BASE}/stock/symbols?${q}`,{headers,signal:c.signal});if(!r.ok)return[];const j=await r.json();return Array.isArray(j?.items)?j.items:[]}catch{return[]}finally{clearTimeout(t)}}
export type AgentPerformance={agent:'fundamental'|'risk'|'forecast'|'comparison'|string;evaluatedCalls:number;directionalAccuracy:number|null;averageSignedReturn:number|null;returnStd:number|null;lastUpdated:string|null;trustReady:boolean;minimumObservedSamples:number};export type KiashaPerformanceSummary={pendingRecommendations:number;evaluatedRecommendationsLowerBound:number;minimumObservedSamples:number;observedTrustActive:boolean;agents:AgentPerformance[];note?:string};export type KiashaPerformanceAgentsResponse={items:AgentPerformance[];minimumObservedSamples:number;observedTrustEnabledFor?:string[]};
async function fetchKiashaJson<T>(path:string,timeoutMs=10_000):Promise<T|null>{const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const headers=await getHeaders(),r=await authFetch(`${KIASHA_API_BASE}${path}`,{headers,signal:c.signal});if(!r.ok)return null;return await r.json()}catch{return null}finally{clearTimeout(t)}}
export async function fetchKiashaPerformanceSummary(timeoutMs=10_000){return fetchKiashaJson<KiashaPerformanceSummary>('/performance/summary',timeoutMs)}export async function fetchKiashaPerformanceAgents(timeoutMs=10_000){return fetchKiashaJson<KiashaPerformanceAgentsResponse>('/performance/agents',timeoutMs)}
export type PaperEquitySnapshot={userId:string;snapshotDate:string;cashBalance:number;positionsValue:number;totalEquity:number;initialCash:number;createdAt:string};export type PaperEquityHistoryResponse={items:PaperEquitySnapshot[];count:number};export async function fetchPaperEquityHistory(limit=400,timeoutMs=10_000){return fetchKiashaJson<PaperEquityHistoryResponse>(`/performance/ai/paper-equity-history?limit=${limit}`,timeoutMs)}
export type KiashaEquitySnapshot={mandateId:string;userId:string;snapshotDate:string;mandateCash:number;positionsValue:number;totalEquity:number;allocatedCash:number;realizedPnL:number;createdAt:string};export type KiashaEquityHistoryResponse={items:KiashaEquitySnapshot[];count:number;valuation:string};export async function fetchKiashaEquityHistory(limit=400,timeoutMs=10_000){return fetchKiashaJson<KiashaEquityHistoryResponse>(`/performance/ai/kiasha-equity-history?limit=${limit}`,timeoutMs)}
