import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { BottomTabInset, Brand, Colors, Fonts, Spacing, ThemeColors } from '@/constants/theme';
import { fetchRecommendation, formatPrice, parsePct, Recommendation, StockItem, MarketSymbolResult } from '@/lib/api';
import { fetchMarketSymbols } from '@/lib/market-symbols';
import { fetchTsetmcHistory, fetchTsetmcQuote, PricePoint } from '@/lib/market-quote';
import { getDemoMode } from '@/lib/demo-mode';
import { isFavorite, toggleFavorite } from '@/lib/favorites';
import { RecommendationCard } from '@/components/recommendation-card';
import { KiashaDecisionCard } from '@/components/kiasha-decision-card';
import { RealTradeGate } from '@/components/real-trade-gate';

function MiniChart({points,colors}:{points:PricePoint[];colors:ThemeColors}){const sample=useMemo(()=>points.length<=24?points:points.filter((_,i)=>i%Math.ceil(points.length/24)===0).slice(-24),[points]);if(sample.length<2)return null;const values=sample.map(p=>p.close),min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min),up=values.at(-1)!>=values[0],accent=up?Brand.stockGreen:Brand.negative;return <View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><View style={styles.head}><Text style={[styles.meta,{color:accent}]}>{up?'▲':'▼'} {(((values.at(-1)!-values[0])/values[0])*100).toFixed(2)}٪</Text><Text style={[styles.cardTitle,{color:colors.text}]}>روند ۶۰ روز</Text></View><View style={styles.bars}>{sample.map((p,i)=><View key={`${p.date}-${i}`} style={[styles.bar,{height:18+((p.close-min)/range)*90,backgroundColor:accent,opacity:.35+i/sample.length*.65}]}/>)}</View></View>}
function Row({label,value,colors}:{label:string;value:string;colors:ThemeColors}){return <View style={[styles.row,{borderBottomColor:colors.backgroundSelected}]}><Text style={[styles.rowValue,{color:colors.text}]}>{value}</Text><Text style={[styles.rowLabel,{color:colors.textSecondary}]}>{label}</Text></View>}

export default function StockDetailScreen(){
 const {code}=useLocalSearchParams<{code:string}>();const colors=useColorScheme()==='dark'?Colors.dark:Colors.light;
 const[symbol,setSymbol]=useState<MarketSymbolResult|null>(null),[item,setItem]=useState<StockItem|null>(null),[history,setHistory]=useState<PricePoint[]>([]),[rec,setRec]=useState<Recommendation|null>(null),[demo,setDemo]=useState(false),[favorite,setFavorite]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[retryInfo,setRetryInfo]=useState<{at:string;ok:boolean}|null>(null);
 const resolve=useCallback(async(forceRetry=false)=>{if(!code)return;try{const candidates=await fetchMarketSymbols({q:code,limit:30});const found=candidates.find(s=>s.code===code)||candidates.find(s=>s.symbol===code)||{code,symbol:code,name:code,market:null};const[recommendation,demoMode]=await Promise.all([fetchRecommendation(found.symbol||found.code,55000),getDemoMode()]);const fundamental=String(recommendation?.codalFundamentals?.symbol??'').trim();const displayTicker=!/^\d+$/.test(found.symbol)?found.symbol:(!/^\d+$/.test(fundamental)&&fundamental?fundamental:found.symbol);const resolved={...found,symbol:displayTicker,name:!/^\d+$/.test(found.name)?found.name:(recommendation?.name||displayTicker||found.name),code:recommendation?.code&&/^\d+$/.test(recommendation.code)?recommendation.code:found.code};setSymbol(resolved);setRec(recommendation);setDemo(demoMode);setFavorite(await isFavorite(resolved.code));const[q,h]=await Promise.all([fetchTsetmcQuote(resolved,7000,false),fetchTsetmcHistory(resolved,60,10000)]);setItem(q);setHistory(h);if(forceRetry)setRetryInfo({at:new Date().toISOString(),ok:Boolean(recommendation)});}finally{setLoading(false);setRefreshing(false)}},[code]);
 useEffect(()=>{setLoading(true);setRetryInfo(null);void resolve(false)},[resolve]);
 const retry=async()=>{setRefreshing(true);await resolve(true)};
 const pct=item?.changePercent!==undefined&&!item?.error?parsePct(item.changePercent):null;const livePrice=item&&!item.error?(item.lastPrice??item.closingPrice??null):null;const onFav=async()=>{if(symbol)setFavorite(await toggleFavorite(symbol))};
 return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={retry} tintColor={Brand.stockGreen}/>} contentContainerStyle={[styles.content,{paddingBottom:BottomTabInset+Spacing.four}]}>
   <View style={styles.header}><Pressable onPress={()=>router.back()} style={[styles.back,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.backText,{color:colors.text}]}>← بازگشت</Text></Pressable><Text style={[styles.headerLabel,{color:colors.textSecondary}]}>جزئیات نماد</Text></View>
   {loading?<ActivityIndicator color={Brand.primary} style={{marginTop:40}}/>:symbol&&item?<><View style={[styles.priceCard,{backgroundColor:colors.backgroundElement}]}><View style={styles.head}><Pressable onPress={onFav} style={[styles.favorite,{backgroundColor:favorite?'#4c1d95':colors.backgroundSelected}]}><Text style={{fontSize:23,color:favorite?'#ffd166':colors.textSecondary}}>{favorite?'★':'☆'}</Text></Pressable><View style={styles.identity}><Text style={[styles.symbol,{color:colors.text}]}>{symbol.symbol}</Text><Text style={[styles.company,{color:colors.textSecondary}]}>{symbol.name}</Text></View></View><View style={styles.priceLine}><Text style={[styles.price,{color:colors.text}]}>{livePrice===null?'—':formatPrice(livePrice)}</Text><Text style={[styles.unit,{color:colors.textSecondary}]}>ریال</Text></View>{pct!==null?<Text style={[styles.change,{color:pct>=0?Brand.stockGreen:Brand.negative}]}>{pct>=0?'▲':'▼'} {Math.abs(pct).toFixed(2)}٪</Text>:<Text style={[styles.meta,{color:colors.textSecondary}]}>قیمت تأییدشده فعلاً دریافت نشد.</Text>}</View>
   {history.length>=2?<MiniChart points={history} colors={colors}/>:<View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.state,{color:colors.textSecondary}]}>تاریخچه معتبر در دسترس نیست؛ نمودار ساختگی نمایش داده نمی‌شود.</Text></View>}
   <View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><Row label="آخرین قیمت" value={`${formatPrice(item.lastPrice)} ریال`} colors={colors}/><Row label="قیمت پایانی" value={`${formatPrice(item.closingPrice)} ریال`} colors={colors}/><Row label="قیمت دیروز" value={`${formatPrice(item.yesterdayPrice)} ریال`} colors={colors}/><Row label="شناسه بازار" value={symbol.code} colors={colors}/></View>
   {rec?<><KiashaDecisionCard rec={rec} colors={colors} demo={demo}/>{demo?<View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><View style={styles.head}><View style={styles.demoBadge}><Text style={styles.demoBadgeText}>DEMO</Text></View><Text style={[styles.cardTitle,{color:colors.text}]}>حالت آزمایشی فعال</Text></View><Text style={[styles.state,{color:colors.textSecondary}]}>معامله آزمایشی در Demo-wallet انجام می‌شود و به کارگزاری ارسال نمی‌شود.</Text></View>:<RealTradeGate colors={colors}/>}<RecommendationCard rec={rec} colors={colors}/></>:<View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.cardTitle,{color:colors.text}]}>تحلیل کیا‌شا دریافت نشد</Text><Text style={[styles.state,{color:colors.textSecondary}]}>می‌توانید دوباره تلاش کنید. اگر منبع داده همچنان پاسخ ندهد، نتیجه به‌صورت شفاف ثبت می‌شود.</Text><Pressable disabled={refreshing} onPress={retry} style={[styles.retry,{backgroundColor:Brand.primary,opacity:refreshing?0.65:1}]}>{refreshing?<ActivityIndicator color="#fff"/>:<Text style={styles.retryText}>تلاش دوباره برای تحلیل کیا‌شا</Text>}</Pressable>{retryInfo?<Text style={[styles.retryResult,{color:retryInfo.ok?Brand.positive:Brand.warning}]}>{retryInfo.ok?'✓ تلاش انجام شد و داده تأییدشده دریافت شد.':'تلاش انجام شد، اما هنوز داده تأییدشده در دسترس نیست.'}{'  '}• {new Date(retryInfo.at).toLocaleTimeString('fa-IR')}</Text>:null}</View>}
   <Text style={[styles.disclaimer,{color:colors.textSecondary}]}>قیمت، تاریخچه و تحلیل فقط از مسیرهای تأییدشده BIAP/TSETMC/CODAL؛ مقدار ناموجود ساخته نمی‌شود.</Text></>:<View style={[styles.card,{backgroundColor:colors.backgroundElement}]}><Text style={[styles.state,{color:colors.textSecondary}]}>اطلاعات این نماد فعلاً قابل دریافت نیست.</Text></View>}
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:Spacing.three},header:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center',paddingVertical:Spacing.three},back:{paddingHorizontal:Spacing.three,paddingVertical:Spacing.two,borderRadius:Spacing.two},backText:{fontFamily:Fonts.sans,fontSize:13},headerLabel:{fontFamily:Fonts.sans,fontSize:12},priceCard:{borderRadius:Spacing.three,padding:Spacing.four,alignItems:'flex-end'},head:{width:'100%',flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center'},identity:{flex:1,alignItems:'flex-end'},favorite:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center'},symbol:{fontFamily:Fonts.sans,fontSize:24,fontWeight:'900'},company:{fontFamily:Fonts.sans,fontSize:11,marginTop:3,textAlign:'right'},priceLine:{flexDirection:'row-reverse',alignItems:'baseline',gap:6,marginTop:Spacing.three},price:{fontFamily:Fonts.mono,fontSize:31,fontWeight:'900'},unit:{fontFamily:Fonts.sans,fontSize:12},change:{fontFamily:Fonts.mono,fontSize:15,fontWeight:'900',marginTop:5},card:{borderRadius:Spacing.three,padding:Spacing.three,marginTop:Spacing.three},cardTitle:{fontFamily:Fonts.sans,fontSize:14,fontWeight:'900',textAlign:'right'},meta:{fontFamily:Fonts.mono,fontSize:10,marginTop:5},bars:{height:115,flexDirection:'row',alignItems:'flex-end',gap:3,marginTop:Spacing.three},bar:{flex:1,borderRadius:3,minWidth:2},row:{flexDirection:'row-reverse',justifyContent:'space-between',paddingVertical:Spacing.three,borderBottomWidth:StyleSheet.hairlineWidth},rowLabel:{fontFamily:Fonts.sans,fontSize:12},rowValue:{fontFamily:Fonts.mono,fontSize:12,fontWeight:'700',maxWidth:'65%'},state:{fontFamily:Fonts.sans,fontSize:11.5,lineHeight:20,textAlign:'right',marginTop:Spacing.two},retry:{width:'100%',paddingVertical:Spacing.three,borderRadius:Spacing.two,alignItems:'center',marginTop:Spacing.three},retryText:{color:'#fff',fontFamily:Fonts.sans,fontSize:13,fontWeight:'900'},retryResult:{fontFamily:Fonts.sans,fontSize:10.5,lineHeight:18,textAlign:'right',marginTop:Spacing.three},demoBadge:{backgroundColor:'#6d28d9',borderRadius:12,paddingHorizontal:8,paddingVertical:4},demoBadgeText:{color:'#fff',fontFamily:Fonts.mono,fontSize:9,fontWeight:'900'},disclaimer:{fontFamily:Fonts.sans,fontSize:10,textAlign:'center',marginVertical:Spacing.three}});