import { useState } from 'react';
import { View, Text, Image, TextInput, Pressable, StyleSheet, KeyboardAvoidingView, Platform, ActivityIndicator, useColorScheme } from 'react-native';
import { Colors, Brand, Fonts, Spacing, Radius, BiapLogo } from '@/constants/theme';
import { API_BASE } from '@/lib/api';
import { setDemoMode } from '@/lib/demo-mode';
import { storeAuthPayload } from '@/lib/auth-session';
import { getClientContext } from '@/lib/activity';

type Props={onLogin:()=>void;onRegister:()=>void};type Mode='login'|'forgot'|'reset';const DEMO_EMAIL='demo@biap.app';

export default function LoginScreen({onLogin,onRegister}:Props){
  const colors=useColorScheme()==='dark'?Colors.dark:Colors.light;const[mode,setMode]=useState<Mode>('login');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[resetCode,setResetCode]=useState('');const[newPassword,setNewPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[loading,setLoading]=useState(false);const[errorMsg,setErrorMsg]=useState('');const[infoMsg,setInfoMsg]=useState('');
  const handleLogin=async()=>{setErrorMsg('');setInfoMsg('');if(!email||!password){setErrorMsg('Enter your email and password.');return}setLoading(true);try{const normalizedEmail=email.trim().toLowerCase();const context=await getClientContext();const res=await fetch(`${API_BASE}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:normalizedEmail,password,...context})});const data=await res.json();if(!res.ok){const detail=typeof data?.detail?.error==='string'?data.detail.error:null;setErrorMsg(data?.error||detail||'Sign in failed.');return}await storeAuthPayload(data);await setDemoMode(normalizedEmail===DEMO_EMAIL);onLogin()}catch{setErrorMsg('Could not connect to the server.')}finally{setLoading(false)}};
  const requestReset=async()=>{setErrorMsg('');setInfoMsg('');if(!email.trim()){setErrorMsg('Enter your email address.');return}setLoading(true);try{const context=await getClientContext();const res=await fetch(`${API_BASE}/auth/forgot-password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.trim().toLowerCase(),...context})});const data=await res.json().catch(()=>({}));if(!res.ok){setErrorMsg(data?.error||'Password reset request failed.');return}setInfoMsg(data?.message||'If the account exists, a recovery code will be sent.');setMode('reset')}catch{setErrorMsg('Could not connect to the server.')}finally{setLoading(false)}};
  const submitReset=async()=>{setErrorMsg('');setInfoMsg('');if(!resetCode.trim()){setErrorMsg('Enter the recovery code.');return}if(newPassword.length<8){setErrorMsg('The new password must contain at least 8 characters.');return}if(newPassword!==confirmPassword){setErrorMsg('The new passwords do not match.');return}setLoading(true);try{const context=await getClientContext();const res=await fetch(`${API_BASE}/auth/reset-password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:resetCode.trim(),newPassword,...context})});const data=await res.json().catch(()=>({}));if(!res.ok){setErrorMsg(data?.error||'The recovery code is invalid.');return}setPassword('');setResetCode('');setNewPassword('');setConfirmPassword('');setMode('login');setInfoMsg(data?.message||'Password changed. You can sign in now.')}catch{setErrorMsg('Could not connect to the server.')}finally{setLoading(false)}};
  const title=mode==='login'?'BIAP Global':mode==='forgot'?'Reset your password':'Set a new password';const subtitle=mode==='login'?'One analysis engine across connected global markets':mode==='forgot'?'Enter the email address for your BIAP account':'Enter the recovery code and your new password';
  return <KeyboardAvoidingView style={[styles.container,{backgroundColor:colors.background}]} behavior={Platform.OS==='ios'?'padding':undefined}><Image source={BiapLogo} style={styles.logo} resizeMode="contain"/><Text style={[styles.title,{color:colors.text}]}>{title}</Text><Text style={[styles.subtitle,{color:colors.textSecondary}]}>{subtitle}</Text><View style={{height:32}}/>
    {mode!=='reset'?<TextInput placeholder="Email" placeholderTextColor={colors.textSecondary} value={email} onChangeText={setEmail} style={[styles.input,{color:colors.text,backgroundColor:colors.backgroundElement,borderColor:colors.backgroundSelected}]} keyboardType="email-address" autoCapitalize="none" autoCorrect={false}/>:null}
    {mode==='login'?<TextInput placeholder="Password" placeholderTextColor={colors.textSecondary} value={password} onChangeText={setPassword} secureTextEntry style={[styles.input,{color:colors.text,backgroundColor:colors.backgroundElement,borderColor:colors.backgroundSelected}]}/>:null}
    {mode==='reset'?<><TextInput placeholder="Recovery code" placeholderTextColor={colors.textSecondary} value={resetCode} onChangeText={setResetCode} autoCapitalize="characters" style={[styles.input,{color:colors.text,backgroundColor:colors.backgroundElement,borderColor:colors.backgroundSelected}]}/><TextInput placeholder="New password (minimum 8 characters)" placeholderTextColor={colors.textSecondary} value={newPassword} onChangeText={setNewPassword} secureTextEntry style={[styles.input,{color:colors.text,backgroundColor:colors.backgroundElement,borderColor:colors.backgroundSelected}]}/><TextInput placeholder="Confirm new password" placeholderTextColor={colors.textSecondary} value={confirmPassword} onChangeText={setConfirmPassword} secureTextEntry style={[styles.input,{color:colors.text,backgroundColor:colors.backgroundElement,borderColor:colors.backgroundSelected}]}/></>:null}
    {errorMsg?<Text style={styles.error}>{errorMsg}</Text>:null}{infoMsg?<Text style={[styles.info,{color:Brand.positive}]}>{infoMsg}</Text>:null}
    <Pressable style={[styles.button,{backgroundColor:Brand.primary,opacity:loading?0.7:1}]} onPress={mode==='login'?handleLogin:mode==='forgot'?requestReset:submitReset} disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>{mode==='login'?'Sign in':mode==='forgot'?'Send recovery code':'Change password'}</Text>}</Pressable>
    {mode==='login'?<><Pressable onPress={()=>{setMode('forgot');setErrorMsg('');setInfoMsg('')}} style={styles.linkButton}><Text style={[styles.linkText,{color:Brand.primary}]}>Forgot password?</Text></Pressable><Pressable onPress={onRegister} style={[styles.buttonOutline,{borderColor:colors.backgroundSelected}]}><Text style={[styles.buttonOutlineText,{color:colors.text}]}>Create account</Text></Pressable></>:<Pressable onPress={()=>{setMode('login');setErrorMsg('')}} style={styles.linkButton}><Text style={[styles.linkText,{color:colors.textSecondary}]}>Back to sign in</Text></Pressable>}
  </KeyboardAvoidingView>;
}
const styles=StyleSheet.create({container:{flex:1,alignItems:'center',justifyContent:'center',paddingHorizontal:Spacing.four},logo:{width:140,height:46},title:{fontSize:22,fontFamily:Fonts.sans,fontWeight:'800',marginTop:Spacing.three,textAlign:'center'},subtitle:{fontSize:13,marginTop:8,textAlign:'center',fontFamily:Fonts.sans},input:{width:'100%',borderWidth:1,borderRadius:Radius.md,paddingHorizontal:Spacing.three,paddingVertical:14,marginBottom:14,fontSize:15,fontFamily:Fonts.sans},button:{width:'100%',borderRadius:Radius.md,paddingVertical:16,alignItems:'center',marginTop:8},buttonText:{color:'#fff',fontSize:15,fontWeight:'800',fontFamily:Fonts.sans},buttonOutline:{width:'100%',borderRadius:Radius.md,paddingVertical:16,alignItems:'center',marginTop:Spacing.two,borderWidth:1},buttonOutlineText:{fontSize:15,fontWeight:'800',fontFamily:Fonts.sans},linkButton:{paddingVertical:12},linkText:{fontSize:12,fontFamily:Fonts.sans},error:{color:'#E15B5B',fontSize:12,marginBottom:8,textAlign:'center',fontFamily:Fonts.sans},info:{fontSize:12,marginBottom:8,textAlign:'center',fontFamily:Fonts.sans,lineHeight:19}});