import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { router } from 'expo-router';
import { BottomTabInset, Brand, Colors, Fonts, MaxContentWidth, Radius, Spacing } from '@/constants/theme';

const STEPS = [
  { n:'1', title:'Choose a country and exchange', body:'Open the Market Selector and choose the country and exchange you want to analyze. The selection changes the market and filing providers, not the BIAP decision engine. Currency, MIC/exchange identity and provider context follow the selected market.', action:'Choose market', route:'/global' },
  { n:'2', title:'Browse or search the exchange', body:'Market shows instruments from the selected exchange. Search by ticker, company or ISIN when supported. Market data is explicitly labelled as Live, Cached or Catalog only. Catalog-only means instrument reference data is available, but verified price/history has not been seeded and cannot support an investment recommendation.', action:'Open Market', route:'/market' },
  { n:'3', title:'Run Kiasha with six scoring agents', body:'Kiasha screens tradability and then evaluates Fundamental, Risk, Forecast, Comparison, Quality and Liquidity. Evidence/Verification checks source coverage, timestamps, freshness and conflicts. Cached verified snapshots keep their original price timestamp so stale data can still be blocked. A new BUY candidate is promoted only when the evidence and confidence gates are satisfied.', action:'Open Kiasha', route:'/kiasha' },
  { n:'4', title:'Read the full stock analysis', body:'The stock page shows price context, valuation, fundamentals, risk metrics, every agent signal and source provenance returned by the backend. Missing values stay missing. If evidence is stale, incomplete or conflicting, NO_RECOMMENDATION is a valid result.', action:'Browse stocks', route:'/market' },
  { n:'5', title:'Compare several markets at once', body:'Portfolio can combine up to four exchanges in the current preview. BIAP scans each exchange independently with the same agent pipeline and clearly separates Live, Cached, Catalog-only and failed markets. Catalog-only markets are excluded from allocation instead of being treated as markets with zero good stocks.', action:'Compare markets', route:'/portfolio' },
  { n:'6', title:'Build a global paper portfolio', body:'Enter capital, base currency, risk tolerance, horizon, maximum positions and cash reserve. Portfolio Agent applies FX conversion and country, sector and position caps. The result explains why each stock was selected and shows a final analytical table with all six agent votes.', action:'Build portfolio', route:'/portfolio' },
  { n:'7', title:'Use Modules with the same company context', body:'Modules use the Selected Company from Market or Kiasha. Public market and filing data are reused where suitable. Modules that require private operational data — such as CRM, customer journey or internal unit economics — ask for a private data connection instead of inventing values.', action:'Open Modules', route:'/modules' },
  { n:'8', title:'Connect private company data only when needed', body:'Data Connections accepts CSV, JSON or Excel and provides paths for CRM, SQL or Custom API integrations. Private company data is separate from public investment evidence and should only supplement fields that cannot be obtained from verified public sources.', action:'Data Connections', route:'/data-connect' },
  { n:'9', title:'Paper first; live execution remains off', body:'Global Portfolio and Execution are research/paper workflows. BIAP Global does not submit live broker orders in this build. Live execution requires a separate broker adapter, permissions, execution controls and validation before it can be enabled.', action:'Execution status', route:'/orders' },
] as const;

export default function HowToScreen(){
  const colors=useColorScheme()==='dark'?Colors.dark:Colors.light;
  return <SafeAreaView style={[s.safe,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={[s.content,{paddingBottom:BottomTabInset+Spacing.four}]}><View style={s.wrap}>
    <View style={s.header}><Text style={[s.title,{color:colors.text}]}>How to use BIAP Global</Text><Text style={[s.sub,{color:colors.textSecondary}]}>Version 0.3.4 • from market selection to evidence-gated global portfolio</Text></View>
    <View style={[s.hero,{backgroundColor:colors.backgroundElement}]}><Text style={s.tag}>BIAP GLOBAL GUIDE</Text><Text style={[s.heroTitle,{color:colors.text}]}>Verified data → agents → evidence → portfolio</Text><Text style={[s.body,{color:colors.textSecondary}]}>The same analysis logic is used across connected countries. What changes by market is the provider layer: exchange data, official filings, identity and currency context. Verified market snapshots are cached for resilience, but their original timestamps remain visible to the Evidence Agent. BIAP does not fill unavailable fields with invented values.</Text></View>
    {STEPS.map(step=><View key={step.n} style={[s.card,{backgroundColor:colors.backgroundElement}]}><View style={s.top}><View style={s.num}><Text style={s.numText}>{step.n}</Text></View><View style={{flex:1}}><Text style={[s.cardTitle,{color:colors.text}]}>{step.title}</Text><Text style={[s.body,{color:colors.textSecondary}]}>{step.body}</Text></View></View><Pressable onPress={()=>router.push(step.route as never)} style={s.action}><Text style={s.actionText}>{step.action} →</Text></Pressable></View>)}
    <View style={[s.rule,{backgroundColor:colors.backgroundElement}]}><Text style={[s.cardTitle,{color:colors.text}]}>Core BIAP rule</Text><Text style={[s.body,{color:colors.textSecondary}]}>Real data, cached verified snapshots, paper portfolios and demo behavior remain separate. Missing or stale evidence may reduce confidence or block a directional result. A blank or NO_RECOMMENDATION outcome is preferable to a confident answer built on unreliable inputs.</Text></View>
  </View></ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1},content:{paddingHorizontal:Spacing.three},wrap:{maxWidth:MaxContentWidth,width:'100%',alignSelf:'center'},header:{paddingTop:Spacing.four,paddingBottom:Spacing.three},title:{fontFamily:Fonts.sans,fontSize:24,fontWeight:'900'},sub:{fontFamily:Fonts.sans,fontSize:10.5,lineHeight:16,marginTop:4},hero:{borderRadius:Radius.lg,padding:Spacing.four,marginBottom:Spacing.three},tag:{fontFamily:Fonts.mono,fontSize:9,fontWeight:'900',color:Brand.primary},heroTitle:{fontFamily:Fonts.sans,fontSize:18,fontWeight:'900',marginTop:6},body:{fontFamily:Fonts.sans,fontSize:10.5,lineHeight:18,marginTop:5},card:{borderRadius:Radius.md,padding:Spacing.three,marginBottom:Spacing.two},top:{flexDirection:'row',gap:Spacing.three,alignItems:'flex-start'},num:{width:34,height:34,borderRadius:17,backgroundColor:Brand.primary,alignItems:'center',justifyContent:'center'},numText:{color:'#fff',fontFamily:Fonts.mono,fontWeight:'900'},cardTitle:{fontFamily:Fonts.sans,fontSize:14,fontWeight:'900'},action:{alignSelf:'flex-start',marginTop:Spacing.two,paddingVertical:5},actionText:{fontFamily:Fonts.sans,fontSize:10,fontWeight:'900',color:Brand.primary},rule:{borderRadius:Radius.md,padding:Spacing.four,marginTop:Spacing.two}});