export type DataSourceKey = 'tsetmc' | 'tindex' | 'codal' | 'company-dataset' | 'crm' | 'sql' | 'custom-api';
export type CompanyMode = 'listed' | 'private' | 'hybrid';

export type DataFieldRequirement = {
  key: string;
  label: string;
  aliases: string[];
  required: boolean;
  autoSources?: DataSourceKey[];
};

export type ModuleDataRequirement = {
  key: string;
  title: string;
  description: string;
  fields: DataFieldRequirement[];
  listedAutoSources: DataSourceKey[];
  privateSources: DataSourceKey[];
  csvTemplate: string;
};

const f = (key: string, label: string, aliases: string[], required = true, autoSources?: DataSourceKey[]): DataFieldRequirement => ({ key, label, aliases, required, autoSources });

export const MODULE_DATA_REQUIREMENTS: Record<string, ModuleDataRequirement> = {
  eda: { key:'eda', title:'EDA Explorer', description:'تحلیل اکتشافی روی هر dataset ساختاریافته.', fields:[f('records','رکوردهای داده',['rows','records','ردیف'])], listedAutoSources:['tsetmc','codal'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'date,metric,value\n1405-01,فروش,1200000' },
  sql: { key:'sql', title:'SQL / Data Query', description:'برای شرکت بورسی داده قابل استخراج BIAP به جدول تحلیلی تبدیل می‌شود؛ داده داخلی فقط در صورت نیاز اضافه می‌شود.', fields:[f('entity','شناسه/نماد یا dataset',['symbol','ticker','نماد','company']),f('columns','ستون‌های قابل تحلیل',['columns','fields','ستون'])], listedAutoSources:['tsetmc','tindex','codal'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'date,customer,product,revenue,cost\n1405-01,مشتری نمونه,خدمت A,1200000,700000' },
  anomaly: { key:'anomaly', title:'تشخیص ناهنجاری', description:'به سری زمانی یا چند دوره داده نیاز دارد.', fields:[f('date','تاریخ/دوره',['date','month','time','تاریخ','ماه']),f('metric','شاخص عددی',['value','sales','revenue','فروش','درآمد'])], listedAutoSources:['tsetmc','tindex'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'date,revenue,cost,transactions\n1405-01,1200000,700000,240' },
  forecast: { key:'forecast', title:'پیش‌بینی آماری', description:'حداقل چند دوره تاریخچه معتبر؛ عدد آینده بدون تاریخچه ساخته نمی‌شود.', fields:[f('date','تاریخ/دوره',['date','month','تاریخ','ماه']),f('target','متغیر هدف',['revenue','sales','price','فروش','درآمد','قیمت'])], listedAutoSources:['tsetmc','tindex','codal'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'month,revenue\n1404-10,1000000\n1404-11,1100000\n1404-12,1250000' },
  'kpi-extract': { key:'kpi-extract', title:'KPI', description:'شاخص‌ها از داده موجود استخراج می‌شوند؛ برای شرکت بورسی ابتدا بازار و CODAL استفاده می‌شود.', fields:[f('period','دوره',['date','month','period','دوره','ماه'],false),f('revenue','فروش/درآمد',['revenue','sales','درآمد','فروش'],false,['codal']),f('cost','هزینه',['cost','expense','هزینه'],false,['codal']),f('customers','مشتری',['customers','customer','مشتری'],false)], listedAutoSources:['tsetmc','tindex','codal'], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'month,revenue,cost,customers,new_customers,conversion,churn\n1405-01,1200000,700000,240,35,4.8,2.1' },
  'business-kpi': { key:'business-kpi', title:'داشبورد KPI کسب‌وکار', description:'رشد فروش، هزینه، مشتری و نرخ‌های عملکردی را در چند دوره مقایسه می‌کند.', fields:[f('period','ماه/دوره',['month','date','ماه','دوره']),f('revenue','فروش/درآمد',['revenue','sales','درآمد','فروش']),f('cost','هزینه',['cost','expense','هزینه']),f('customers','مشتری فعال',['customers','activecustomers','مشتری']),f('newCustomers','مشتری جدید',['newcustomers','مشتریجدید'],false),f('conversion','نرخ تبدیل',['conversion','نرختبدیل'],false),f('churn','نرخ ریزش',['churn','ریزش'],false)], listedAutoSources:['codal','tsetmc','tindex'], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'month,revenue,cost,customers,new_customers,conversion,churn\n1405-01,1200000,700000,240,35,4.8,2.1' },
  dashboard: { key:'dashboard', title:'BI Dashboard', description:'برای طراحی داشبورد، شاخص‌ها و ابعاد واقعی dataset لازم است.', fields:[f('metrics','حداقل یک KPI عددی',['revenue','sales','customers','فروش','درآمد','مشتری'])], listedAutoSources:['tsetmc','tindex','codal'], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'month,revenue,cost,customers\n1405-01,1200000,700000,240' },
  governance: { key:'governance', title:'KPI Governance', description:'تعریف KPI، مالک، هدف و آستانه هشدار.', fields:[f('kpi','نام KPI',['kpi','metric','شاخص']),f('owner','مالک KPI',['owner','department','مالک','دپارتمان'],false),f('target','هدف',['target','goal','هدف'],false)], listedAutoSources:['codal','tsetmc'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'kpi,value,target,owner,frequency\nConversion,4.8,5.0,Sales,weekly' },
  report: { key:'report', title:'گزارش تحلیلی', description:'از هر داده واقعی متصل می‌تواند گزارش بسازد.', fields:[f('data','داده قابل تحلیل',['value','metric','revenue','sales','داده'])], listedAutoSources:['tsetmc','tindex','codal'], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'month,revenue,cost,customers\n1405-01,1200000,700000,240' },
  swot: { key:'swot', title:'SWOT + رقبا', description:'قوت/ضعف از داده داخلی و فرصت/تهدید از داده بازار/رقبا استخراج می‌شود.', fields:[f('companyMetrics','شاخص‌های شرکت',['revenue','sales','customers','درآمد','فروش']),f('competitor','داده رقبا',['competitor','marketshare','رقیب','سهمبازار'],false)], listedAutoSources:['tsetmc','tindex','codal'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'competitor,price,market_share,customer_score\nرقیب الف,500000,35,4.2' },
  'market-entry': { key:'market-entry', title:'ورود به بازار جدید', description:'برای بازار جدید به وضعیت فعلی شرکت و مشخصات بازار هدف نیاز دارد.', fields:[f('revenue','فروش فعلی',['revenue','sales','فروش','درآمد']),f('targetMarket','بازار هدف',['targetmarket','market','بازارهدف','بازار']),f('marketSize','اندازه بازار',['marketsize','tam','اندازهبازار'],false),f('competitors','رقبا',['competitor','رقیب'],false)], listedAutoSources:['codal','tsetmc'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'target_market,market_size,competitor,company_revenue\nتهران,5000000000,رقیب الف,120000000' },
  journey: { key:'journey', title:'Journey Map', description:'مراحل قیف، تبدیل، ریزش و رضایت مشتری.', fields:[f('stage','مرحله سفر',['stage','step','مرحله']),f('conversion','نرخ تبدیل',['conversion','نرختبدیل'],false),f('dropoff','ریزش',['dropoff','churn','ریزش'],false),f('satisfaction','رضایت',['satisfaction','nps','csat','رضایت'],false)], listedAutoSources:[], privateSources:['company-dataset','crm','sql','custom-api'], csvTemplate:'stage,users,conversion,dropoff,satisfaction\nآگاهی,1000,45,10,4.1' },
  crm: { key:'crm', title:'CRM + Pipeline', description:'Lead scoring، Pipeline، احتمال بستن و اقدام بعدی.', fields:[f('customer','مشتری/Lead',['customer','lead','مشتری','سرنخ']),f('stage','مرحله',['stage','pipeline','مرحله']),f('dealValue','ارزش قرارداد',['dealvalue','amount','value','ارزشقرارداد']),f('probability','احتمال بستن',['probability','winprobability','احتمال']),f('lastContact','آخرین تماس',['lastcontact','آخرینتماس'],false)], listedAutoSources:[], privateSources:['crm','company-dataset','sql','custom-api'], csvTemplate:'customer,industry,stage,deal_value,last_contact,probability\nشرکت آلفا,فناوری,مذاکره,250000000,1405-01-15,75' },
  campaign: { key:'campaign', title:'کمپین بازاریابی', description:'فروش تاریخی، کانال، بودجه و مخاطب هدف.', fields:[f('revenue','فروش',['revenue','sales','فروش']),f('channel','کانال',['channel','کانال'],false),f('budget','بودجه بازاریابی',['budget','marketingcost','بودجه'],false),f('audience','مخاطب هدف',['audience','segment','مخاطب'],false)], listedAutoSources:['codal'], privateSources:['company-dataset','crm','sql','custom-api'], csvTemplate:'month,channel,revenue,marketing_cost,leads,conversions\n1405-01,Online,1200000,150000,300,42' },
  pricing: { key:'pricing', title:'قیمت‌گذاری هوشمند', description:'قیمت واقعی محصول/خدمت، هزینه و حجم فروش لازم است. داده بورسی به‌تنهایی معمولاً برای قیمت محصول کافی نیست.', fields:[f('price','قیمت فروش',['price','unitprice','قیمت']),f('cost','هزینه تمام‌شده',['cost','unitcost','هزینه']),f('units','حجم/تعداد فروش',['units','quantity','qty','تعداد']),f('competitorPrice','قیمت رقبا',['competitorprice','قیمترقیب'],false),f('conversion','نرخ تبدیل',['conversion','نرختبدیل'],false)], listedAutoSources:['codal'], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'product,price,cost,quantity,competitor_price,conversion\nخدمت A,1200000,700000,240,1250000,4.8' },
  plan: { key:'plan', title:'Business Plan', description:'برای طرح کسب‌وکار داده مالی، مشتری و بازار لازم است.', fields:[f('revenue','درآمد',['revenue','sales','درآمد','فروش']),f('cost','هزینه',['cost','expense','هزینه']),f('customers','مشتری',['customers','مشتری'],false),f('market','بازار هدف',['market','tam','sam','som','بازار'],false)], listedAutoSources:['codal','tsetmc'], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'month,revenue,cost,customers,market_size\n1405-01,1200000,700000,240,5000000000' },
  'executive-report': { key:'executive-report', title:'گزارش مدیریتی', description:'عملکرد دوره جاری و مقایسه با دوره قبل.', fields:[f('period','دوره',['month','date','period','ماه']),f('revenue','فروش/درآمد',['revenue','sales','درآمد','فروش']),f('cost','هزینه',['cost','expense','هزینه']),f('target','هدف',['target','goal','هدف'],false)], listedAutoSources:['codal','tsetmc','tindex'], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'month,revenue,cost,target\n1405-01,1200000,700000,1300000' },
  'financial-model': { key:'financial-model', title:'Financial Modeling', description:'درآمد، هزینه و چند دوره تاریخی؛ برای شرکت بورسی صورت‌های مالی CODAL اولویت دارد.', fields:[f('period','دوره',['month','date','period','ماه']),f('revenue','درآمد',['revenue','sales','درآمد','فروش'],true,['codal']),f('cost','هزینه',['cost','expense','هزینه'],true,['codal']),f('customers','مشتری',['customers','مشتری'],false)], listedAutoSources:['codal','tsetmc','tindex'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'month,revenue,cost,customers\n1404-10,1000000,650000,220\n1404-11,1100000,690000,230\n1404-12,1250000,720000,245' },
  scenario: { key:'scenario', title:'Scenario Analysis', description:'داده فعلی + فرضیات رشد/هزینه؛ سناریو بدون شواهد عدد جعلی تولید نمی‌کند.', fields:[f('baseline','داده پایه',['revenue','sales','cost','درآمد','فروش','هزینه']),f('assumptions','فرضیات',['growth','assumption','نرخرشد','فرض'],false)], listedAutoSources:['codal','tsetmc','tindex'], privateSources:['company-dataset','sql','custom-api'], csvTemplate:'month,revenue,cost,growth_assumption\n1405-01,1200000,700000,8' },
  unit: { key:'unit', title:'Unit Economics', description:'CAC، LTV و Payback نیازمند داده مشتری و هزینه جذب است.', fields:[f('marketingCost','هزینه بازاریابی',['marketingcost','adspend','هزینهبازاریابی']),f('newCustomers','مشتری جدید',['newcustomers','مشتریجدید']),f('revenue','درآمد',['revenue','sales','درآمد']),f('churn','نرخ ریزش',['churn','ریزش'],false)], listedAutoSources:['codal'], privateSources:['company-dataset','crm','sql','custom-api'], csvTemplate:'month,marketing_cost,new_customers,revenue,churn\n1405-01,150000,35,1200000,2.1' },
  mbr: { key:'mbr', title:'گزارش MBR', description:'حداقل ماه جاری و ماه قبل برای مرور عملکرد ماهانه.', fields:[f('period','ماه',['month','period','ماه']),f('revenue','درآمد',['revenue','sales','درآمد']),f('cost','هزینه',['cost','expense','هزینه']),f('kpi','KPI',['kpi','metric','شاخص'],false)], listedAutoSources:['codal','tsetmc','tindex'], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'month,revenue,cost,customers\n1404-12,1100000,690000,230\n1405-01,1200000,700000,240' },
  voc: { key:'voc', title:'VOC + Friction Points', description:'صدای مشتری از NPS/CSAT، شکایت، نظر و ریزش استخراج می‌شود.', fields:[f('feedback','نظر/شکایت',['feedback','comment','complaint','نظر','شکایت']),f('score','امتیاز رضایت',['nps','csat','score','رضایت'],false),f('churn','ریزش',['churn','ریزش'],false)], listedAutoSources:[], privateSources:['crm','company-dataset','sql','custom-api'], csvTemplate:'customer,feedback,nps,csat,churn\nمشتری ۱,فرآیند پرداخت طولانی بود,6,3,0' },
  behavior: { key:'behavior', title:'رفتار کاربر', description:'برای Funnel و Churn به رویدادهای رفتاری یا شمارش مراحل نیاز است.', fields:[f('stage','مرحله Funnel',['stage','event','مرحله','رویداد']),f('users','تعداد کاربر',['users','count','کاربر']),f('conversion','نرخ تبدیل',['conversion','نرختبدیل'],false),f('churn','نرخ بازگشت/ریزش',['churn','retention','ریزش','بازگشت'],false)], listedAutoSources:[], privateSources:['company-dataset','sql','crm','custom-api'], csvTemplate:'stage,users,conversion,churn\nبازدید,1000,35,0\nثبت نام,350,40,5\nخرید,140,100,8' },
};

export function requirementFor(key: string): ModuleDataRequirement | null {
  return MODULE_DATA_REQUIREMENTS[key] ?? null;
}

export function sourceLabel(source: DataSourceKey): string {
  return ({ tsetmc:'TSETMC', tindex:'Tindex', codal:'CODAL', 'company-dataset':'Excel / CSV / JSON', crm:'CRM / ERP', sql:'SQL', 'custom-api':'Custom API' } as Record<DataSourceKey,string>)[source];
}

export function normalizeColumn(value: string): string {
  return value.toLowerCase().replace(/[\s_\-()%]/g,'').replace(/ي/g,'ی').replace(/ك/g,'ک');
}

export function matchRequirementColumns(key: string, columns: string[]): { matched: DataFieldRequirement[]; missing: DataFieldRequirement[] } {
  const req = requirementFor(key);
  if (!req) return { matched: [], missing: [] };
  const normalized = columns.map(normalizeColumn);
  const matched = req.fields.filter(field => field.aliases.some(alias => normalized.some(column => column.includes(normalizeColumn(alias)))));
  const missing = req.fields.filter(field => field.required && !matched.includes(field));
  return { matched, missing };
}
